package com.sighs.apricityui.instance.element;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import com.sighs.apricityui.ApricityUI;
import com.sighs.apricityui.event.MouseEvent;
import com.sighs.apricityui.init.Document;
import com.sighs.apricityui.init.Drawer;
import com.sighs.apricityui.init.Element;
import com.sighs.apricityui.instance.container.visual.SlotVisualRules;
import com.sighs.apricityui.registry.annotation.ElementRegister;
import com.sighs.apricityui.render.Base;
import net.minecraft.client.Minecraft;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.TagParser;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.RecipeType;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 统一槽位元素：同时承载 bound（真实菜单槽位）与 virtual（展示槽位）能力。
 */
@ElementRegister(Slot.TAG_NAME)
public class Slot extends MinecraftElement {
    public static final String TAG_NAME = "SLOT";
    public static final String MODE_BOUND = "bound";
    public static final String MODE_VIRTUAL = "virtual";
    public static final ResourceLocation FURNACE_FUEL_VIRTUAL_TAG = ApricityUI.id("furnace_fuels");
    private static final String GENERATED_REPEAT = "slot-repeat";
    private static final String GENERATED_REPEAT_RUNTIME = "slot-repeat-runtime";
    private static final String GENERATED_PLAYER_AUTO = "player-auto";
    private static final String STATE_CLASS_HOVERED = "apricity-slot-hovered";
    private static final String STATE_CLASS_ACTIVE = "apricity-slot-active";
    private static final String STATE_CLASS_DISABLED = "apricity-slot-disabled";
    private static final String STATE_CLASS_HAS_ITEM = "apricity-slot-has-item";
    private static final long DEFAULT_ROTATE_INTERVAL_MS = 1000L;
    private static final String TAG_CANDIDATE_CACHE_KEY = "minecraft-element:slot-tag-candidates";

    private String resolvedItemToken = "";
    private ResourceLocation resolvedTagId = null;
    private List<ItemStack> candidates = List.of();
    private int candidateIndex = 0;
    private long nextRotateAtMillis = 0L;
    private String runtimeClassCache = null;

    public Slot(Document document) {
        this(document, true);
    }

    private Slot(Document document, boolean enableDefaultListeners) {
        super(document, TAG_NAME);
        if (enableDefaultListeners) {
            registerDefaultListeners();
        }
    }

    /**
     * 清理运行时自动生成的槽位（当前仅 player-auto）。
     */
    public static void cleanupRuntimeGeneratedSlots(Document document) {
        if (document == null) return;
        List<Element> snapshot = new ArrayList<>(document.getElements());
        for (Element element : snapshot) {
            if (!(element instanceof Slot slot)) continue;
            if (!slot.isPlayerAutoGenerated()) continue;
            slot.remove();
        }
    }

    public static String furnaceFuelVirtualTagLiteral() {
        return "#" + FURNACE_FUEL_VIRTUAL_TAG;
    }

    public static void clearCandidateCache() {
        clearGlobalCache(TAG_CANDIDATE_CACHE_KEY);
    }

    @SuppressWarnings("unchecked")
    private static Map<ResourceLocation, List<ItemStack>> tagCandidateCache() {
        return (Map<ResourceLocation, List<ItemStack>>) computeGlobalCacheIfAbsent(
                TAG_CANDIDATE_CACHE_KEY,
                ConcurrentHashMap::new
        );
    }

    private static List<ItemStack> buildCandidatesByTag(ResourceLocation tagId) {
        ArrayList<ItemStack> result = new ArrayList<>();
        if (FURNACE_FUEL_VIRTUAL_TAG.equals(tagId)) {
            for (Item item : BuiltInRegistries.ITEM) {
                ItemStack stack = new ItemStack(item);
                if (stack.getBurnTime(RecipeType.SMELTING) <= 0) continue;
                result.add(stack);
            }
        } else {
            TagKey<Item> tagKey = TagKey.create(Registries.ITEM, tagId);
            for (Item item : BuiltInRegistries.ITEM) {
                ItemStack stack = new ItemStack(item);
                if (stack.is(tagKey)) result.add(stack);
            }
        }
        result.sort(Comparator.comparing(stack -> {
            ResourceLocation id = BuiltInRegistries.ITEM.getKey(stack.getItem());
            return id == null ? "" : id.toString();
        }));
        return List.copyOf(result);
    }

    private static int parsePositiveInt(String raw, int fallback) {
        if (raw == null || raw.isBlank()) return fallback;
        try {
            int parsed = Integer.parseInt(raw.trim());
            return parsed > 0 ? parsed : fallback;
        } catch (NumberFormatException ignored) {
            return fallback;
        }
    }

    private static long parsePositiveLong(String raw, long fallback) {
        if (raw == null || raw.isBlank()) return fallback;
        try {
            long parsed = Long.parseLong(raw.trim());
            return parsed > 0 ? parsed : fallback;
        } catch (NumberFormatException ignored) {
            return fallback;
        }
    }

    private String getFirstNonBlankAttribute(String... keys) {
        if (keys == null || keys.length == 0) return null;
        for (String key : keys) {
            if (key == null || key.isBlank()) continue;
            String value = getAttribute(key);
            if (value == null || value.isBlank()) continue;
            return value;
        }
        return null;
    }

    private void registerDefaultListeners() {
        addEventListener("mousedown", this::onMouseDown);
        addEventListener("mouseup", this::onMouseUp);
        addEventListener("mousemove", this::onMouseMove);
        addEventListener("mouseenter", this::onMouseEnter);
        addEventListener("mouseout", this::onMouseOut);
    }

    private void onMouseDown(com.sighs.apricityui.init.Event event) {
        if (!isBoundMode()) return;
        if (controller != null && validBinding && event instanceof MouseEvent mouseEvent) {
            mouseEvent.stopPropagation();
            controller.handleSlotMouseDown(this, mouseEvent);
        }
    }

    private void onMouseUp(com.sighs.apricityui.init.Event event) {
        if (!isBoundMode()) return;
        if (controller != null && validBinding && event instanceof MouseEvent mouseEvent) {
            mouseEvent.stopPropagation();
            controller.handleSlotMouseUp(this, mouseEvent);
        }
    }

    private void onMouseMove(com.sighs.apricityui.init.Event event) {
        if (!isBoundMode()) return;
        if (controller != null && validBinding && event instanceof MouseEvent mouseEvent) {
            mouseEvent.stopPropagation();
        }
    }

    private void onMouseEnter(com.sighs.apricityui.init.Event event) {
        setHover(true);
        if (!isBoundMode()) return;
        if (controller != null && validBinding) {
            controller.setHoveredSlot(boundSlotIndex);
        }
    }

    private void onMouseOut(com.sighs.apricityui.init.Event event) {
        setHover(false);
        if (!isBoundMode()) return;
        if (controller != null && validBinding) {
            controller.clearHoveredSlot(boundSlotIndex);
        }
    }

    public String getMode() {
        String rawMode = getAttribute("mode");
        if (rawMode != null && !rawMode.isBlank()) {
            String normalized = rawMode.trim().toLowerCase(Locale.ROOT);
            if (MODE_BOUND.equals(normalized)) return MODE_BOUND;
            if (MODE_VIRTUAL.equals(normalized)) return MODE_VIRTUAL;
        }
        return hasAncestor(Container.class) ? MODE_BOUND : MODE_VIRTUAL;
    }

    @Override
    public MinecraftBindingMode getBindingMode() {
        return MODE_BOUND.equals(getMode()) ? MinecraftBindingMode.BOUND : MinecraftBindingMode.VIRTUAL;
    }

    public int getRepeatCount() {
        return parsePositiveInt(getAttribute("repeat"), 1);
    }

    public boolean isGeneratedSlot() {
        String source = getGeneratedSourceTag();
        return GENERATED_REPEAT.equals(source)
                || GENERATED_REPEAT_RUNTIME.equals(source)
                || GENERATED_PLAYER_AUTO.equals(source);
    }

    public boolean isRuntimeRepeatProxy() {
        return GENERATED_REPEAT_RUNTIME.equals(getGeneratedSourceTag());
    }

    public boolean isPlayerAutoGenerated() {
        return GENERATED_PLAYER_AUTO.equals(getGeneratedSourceTag());
    }

    private String getGeneratedSourceTag() {
        return getAttribute("data-generated");
    }

    public int getSlotIndex() {
        String raw = getAttribute("slot-index");
        try {
            return Integer.parseInt(raw);
        } catch (NumberFormatException ignored) {
            return -1;
        }
    }

    public boolean isDisabled() {
        return Boolean.parseBoolean(getAttribute("disabled"));
    }

    public boolean shouldAcceptPointer() {
        String pointerRaw = getFirstNonBlankAttribute(
                "pointer",
                "accept-pointer",
                "acceptpointer",
                "acceptPointer",
                "hit"
        );
        return SlotVisualRules.resolvePointerEnabled(pointerRaw, true);
    }

    public int resolveSlotSizeHint(int fallback) {
        Integer parsed = SlotVisualRules.parsePositiveInt(getFirstNonBlankAttribute("size", "slot-size"));
        if (parsed == null) return fallback;
        return parsed;
    }

    public boolean shouldRenderBackground() {
        return SlotVisualRules.resolveRenderBackground(getAttribute("render"), true);
    }

    public boolean shouldRenderItem() {
        return SlotVisualRules.resolveRenderItem(getAttribute("render"), true);
    }

    public float resolveIconScale(float fallback) {
        Float parsed = SlotVisualRules.parsePositiveFloat(getFirstNonBlankAttribute("icon-scale", "iconscale", "iconScale", "scale"));
        if (parsed == null) return fallback;
        return parsed;
    }

    public int resolvePadding(int fallback) {
        Integer parsed = SlotVisualRules.parseNonNegativeInt(getFirstNonBlankAttribute("padding"));
        if (parsed == null) return Math.max(0, fallback);
        return parsed;
    }

    public int resolveZIndex(int fallback) {
        Integer parsed = SlotVisualRules.parseSignedInt(getFirstNonBlankAttribute("z-index", "zindex", "zIndex", "z"));
        if (parsed == null) return fallback;
        return parsed;
    }

    @Override
    public boolean canFocus() {
        return isBoundMode();
    }

    /**
     * 创建仅用于绑定与布局计算的 repeat 运行时代理，不插入文档节点。
     */
    public Slot createRuntimeRepeatSlotProxy(int localSlotIndex, int repeatIndex) {
        Slot clone = new Slot(document, false);
        LinkedHashMap<String, String> updates = new LinkedHashMap<>(getAttributes());
        updates.put("repeat", "1");
        updates.put("data-generated", GENERATED_REPEAT_RUNTIME);
        updates.put("data-repeat-index", String.valueOf(repeatIndex));
        if (localSlotIndex >= 0) {
            updates.put("slot-index", String.valueOf(localSlotIndex));
        } else {
            updates.remove("slot-index");
        }
        clone.beginAttributeBatch();
        try {
            for (Map.Entry<String, String> entry : updates.entrySet()) {
                clone.putAttributeSilently(entry.getKey(), entry.getValue());
            }
        } finally {
            clone.endAttributeBatch(false);
        }
        clone.parentElement = parentElement;
        clone.depth = depth;
        if (clone.parentElement != null) {
            clone.depth = clone.parentElement.getDepth() + 1;
        }
        // repeat 代理默认复用模板槽位样式缓存，避免每个副本都重新执行一次选择器匹配。
        clone.cssCache = new HashMap<>(cssCache);
        return clone;
    }

    public Element resolveLayoutAnchor(Container ownerContainer) {
        Element anchor = parentElement;
        if (anchor == null || anchor instanceof Container) {
            return ownerContainer;
        }
        return anchor;
    }

    public String getBackgroundImageCandidate() {
        com.sighs.apricityui.style.Background background = com.sighs.apricityui.style.Background.of(this);
        String rawPath = background == null ? null : background.imagePath;
        if (rawPath == null || rawPath.isBlank() || "unset".equals(rawPath)) return null;
        return rawPath;
    }

    @Override
    public void drawPhase(PoseStack poseStack, Base.RenderPhase phase) {
        if (runtimeHidden) return;
        if (!shouldRenderBackground()
                && (phase == Base.RenderPhase.SHADOW
                || phase == Base.RenderPhase.BODY
                || phase == Base.RenderPhase.BORDER)) {
            return;
        }
        super.drawPhase(poseStack, phase);
    }

    @Override
    public void tick() {
        super.tick();
        if (!isVirtualMode()) return;
        if (isHover) return;
        if (candidates.size() <= 1) return;

        long now = System.currentTimeMillis();
        long interval = Math.max(200L, parsePositiveLong(getAttribute("rotate-interval"), DEFAULT_ROTATE_INTERVAL_MS));
        if (nextRotateAtMillis <= 0L) {
            nextRotateAtMillis = now + interval;
            return;
        }

        if (now < nextRotateAtMillis) return;
        candidateIndex = (candidateIndex + 1) % candidates.size();
        nextRotateAtMillis = now + interval;
    }

    public ItemStack resolveDisplayStack() {
        refreshCandidatesIfNeeded();
        if (candidates.isEmpty()) return ItemStack.EMPTY;

        if (candidateIndex < 0 || candidateIndex >= candidates.size()) {
            candidateIndex = 0;
        }

        ItemStack stack = candidates.get(candidateIndex).copy();
        if (stack.getCount() <= 0) {
            stack.setCount(1);
        }
        return stack;
    }

    @Override
    public ItemStack getTooltipStack() {
        if (!isVirtualMode()) return ItemStack.EMPTY;
        return resolveDisplayStack();
    }

    @Override
    public void renderTooltip(net.minecraft.client.gui.GuiGraphics guiGraphics, int mouseX, int mouseY) {
        ItemStack stack = getTooltipStack();
        if (stack.isEmpty()) return;
        guiGraphics.renderTooltip(Minecraft.getInstance().font, stack, mouseX, mouseY);
    }

    @Override
    protected void onBoundToSlot(com.sighs.apricityui.instance.container.runtime.ContainerEngine.Controller controller,
                                 String containerId,
                                 int slotIndex) {
        runtimeClassCache = null;
        setAttributesBatch(Map.of(
                "data-bound", "true",
                "data-container", containerId == null ? "" : containerId,
                "data-slot-index", String.valueOf(slotIndex)
        ), true);
    }

    @Override
    protected void onUnboundFromSlot() {
        runtimeClassCache = null;
        setAttributesBatch(Map.of(
                "data-bound", "false",
                "data-container", "",
                "data-slot-index", "-1"
        ), true);
    }

    /**
     * 批量设置 recipe 生成槽位的公共元数据，避免重复触发 updateCSS。
     */
    public void applyRecipeSlotMeta(String className, String generatedTag) {
        setAttributesBatch(Map.of(
                "class", className == null ? "" : className,
                "data-generated", generatedTag == null ? "" : generatedTag
        ), true);
    }

    /**
     * 批量设置 player 自动注入槽位的公共属性。
     */
    public void applyImplicitPlayerMeta(int localSlotIndex, String part) {
        setAttributesBatch(Map.of(
                "mode", MODE_BOUND,
                "slot-index", String.valueOf(Math.max(0, localSlotIndex)),
                "data-generated", "player-auto",
                "part", part == null ? "inv" : part
        ), true);
    }

    public void applyPreviewEntry(Recipe.PreviewEntry entry, int slotSize, boolean absolute, int marginBottom) {
        String style = absolute
                ? "position:absolute;display:block;left:%dpx;top:%dpx;width:%dpx;height:%dpx;".formatted(entry.x(), entry.y(), slotSize, slotSize)
                : "position:static;display:block;width:%dpx;height:%dpx;margin-bottom:%dpx;".formatted(slotSize, slotSize, Math.max(0, marginBottom));
        setAttributesBatch(Map.of(
                "mode", MODE_VIRTUAL,
                "data-role", entry.role().name().toLowerCase(Locale.ROOT),
                "data-preview-x", String.valueOf(entry.x()),
                "data-preview-y", String.valueOf(entry.y()),
                "data-preview-absolute", String.valueOf(absolute),
                "style", style
        ), true);
        innerText = buildLiteralWithCount(entry.itemLiteral(), Math.max(1, entry.count()));
        requestRelayout();
        if (document != null && parentElement != null) {
            document.markDirty(parentElement, Drawer.RELAYOUT);
        }
    }

    private void refreshCandidatesIfNeeded() {
        String normalized = resolveItemLiteral();
        if (normalized.equals(resolvedItemToken)) return;

        resolvedItemToken = normalized;
        resolvedTagId = null;
        candidates = List.of();
        candidateIndex = 0;
        nextRotateAtMillis = 0L;

        if (normalized.isBlank()) return;
        if (normalized.startsWith("#")) {
            ResourceLocation tagId = ResourceLocation.tryParse(normalized.substring(1));
            if (tagId == null) return;
            resolvedTagId = tagId;
            candidates = tagCandidateCache().computeIfAbsent(tagId, Slot::buildCandidatesByTag);
            return;
        }

        ItemStack parsed = parseItemLiteral(normalized);
        if (!parsed.isEmpty()) {
            candidates = List.of(parsed);
        }
    }

    private String resolveItemLiteral() {
        return normalizeItemLiteral(innerText);
    }

    private static String normalizeItemLiteral(String raw) {
        if (raw == null) return "";
        String normalized = raw.trim();
        if (normalized.isBlank()) return "";
        if (normalized.length() >= 2) {
            char first = normalized.charAt(0);
            char last = normalized.charAt(normalized.length() - 1);
            boolean quoted = (first == '"' && last == '"') || (first == '\'' && last == '\'');
            if (quoted) {
                normalized = normalized.substring(1, normalized.length() - 1).trim();
            }
        }
        return normalized;
    }

    public static String buildLiteralWithCount(String rawLiteral, int requestedCount) {
        String normalized = normalizeItemLiteral(rawLiteral);
        if (normalized.isBlank()) return "";

        ItemStack parsed = parseItemLiteral(normalized);
        if (parsed.isEmpty()) return normalized;

        int safeCount = Math.max(1, Math.min(parsed.getMaxStackSize(), requestedCount));
        ResourceLocation itemId = BuiltInRegistries.ITEM.getKey(parsed.getItem());
        if (itemId == null) return normalized;
        return "{id:\"%s\",Count:%db}".formatted(itemId, safeCount);
    }

    private static ItemStack parseItemLiteral(String literal) {
        if (literal == null || literal.isBlank()) return ItemStack.EMPTY;

        // 支持 ItemStack NBT 全格式：{id:"minecraft:diamond",Count:1b,tag:{...}}
        if (literal.startsWith("{") && literal.endsWith("}")) {
            try {
                CompoundTag stackTag = TagParser.parseTag(literal);
                String idRaw = stackTag.getString("id");
                ResourceLocation itemId = ResourceLocation.tryParse(idRaw);
                if (itemId == null || !BuiltInRegistries.ITEM.containsKey(itemId)) return ItemStack.EMPTY;
                ItemStack parsed = new ItemStack(BuiltInRegistries.ITEM.get(itemId));
                int count = stackTag.contains("Count") ? stackTag.getInt("Count") : 1;
                parsed.setCount(Math.max(1, Math.min(parsed.getMaxStackSize(), count)));
                return parsed;
            } catch (CommandSyntaxException ignored) {
                return ItemStack.EMPTY;
            }
        }

        int nbtStart = literal.indexOf('{');
        String itemLiteral = nbtStart >= 0 ? literal.substring(0, nbtStart).trim() : literal;
        if (itemLiteral.isBlank()) return ItemStack.EMPTY;

        ResourceLocation itemId = ResourceLocation.tryParse(itemLiteral);
        if (itemId == null || !BuiltInRegistries.ITEM.containsKey(itemId)) return ItemStack.EMPTY;
        Item item = BuiltInRegistries.ITEM.get(itemId);
        ItemStack stack = new ItemStack(item);

        // 支持 minecraft:diamond{display:{Name:'{"text":"A"}'}}
        return stack;
    }

    public void syncRuntimeStateClasses(boolean hovered, boolean active, boolean disabled, boolean hasItem) {
        String rawClassNames = getAttribute("class");
        LinkedHashSet<String> mergedClasses = new LinkedHashSet<>();
        if (rawClassNames != null && !rawClassNames.isBlank()) {
            for (String className : rawClassNames.trim().split("\\s+")) {
                if (className.isBlank()) continue;
                if (STATE_CLASS_HOVERED.equals(className)
                        || STATE_CLASS_ACTIVE.equals(className)
                        || STATE_CLASS_DISABLED.equals(className)
                        || STATE_CLASS_HAS_ITEM.equals(className)) {
                    continue;
                }
                mergedClasses.add(className);
            }
        }
        if (hovered) mergedClasses.add(STATE_CLASS_HOVERED);
        if (active) mergedClasses.add(STATE_CLASS_ACTIVE);
        if (disabled) mergedClasses.add(STATE_CLASS_DISABLED);
        if (hasItem) mergedClasses.add(STATE_CLASS_HAS_ITEM);

        String nextClassNames = String.join(" ", mergedClasses).trim();
        String normalizedCurrentClassNames = rawClassNames == null ? "" : rawClassNames.trim();
        if (Objects.equals(nextClassNames, normalizedCurrentClassNames)) {
            runtimeClassCache = nextClassNames;
            return;
        }
        if (Objects.equals(runtimeClassCache, nextClassNames)) return;
        runtimeClassCache = nextClassNames;
        setAttribute("class", nextClassNames);
    }

}
